apiVersion: skaffold/v4beta6
kind: Config

build:
  local:
    push: false
  artifacts:
    - image: eureka
      context: ../cd_eureka
    - image: auth-service
      context: ../cd_auth
    - image: generator-service
      context: ../cd_generator
    - image: mock-service
      context: ../cd_mock
    - image: desc-service
      context: ../cd_desc
    - image: site-service
      context: ../cd_site
    - image: notification-service
      context: ../cd_notification

manifests:
  rawYaml:
    - k8s/config/*.yaml
    - k8s/secrets/*.yaml
    - k8s/db/*.yaml
    - k8s/apps/*.yaml
    
portForward:
  - resourceType: service
    resourceName: eureka
    port: 9009        # порт внутри кластера
    localPort: 9009   # порт, который будет доступен на вашем localhost
  - resourceType: service
    resourceName: site-service
    port: 8080        # порт внутри кластера
    localPort: 8080   # порт, который будет доступен на вашем localhost
  - resourceType: service
    resourceName: db-auth
    port: 5432
    localPort: 5433 # Порт, который вы укажете в pgAdmin (localhost:5433)
  - resourceType: service
    resourceName: db-generator
    port: 5432
    localPort: 5434 # Порт, который вы укажете в pgAdmin (localhost:5434)
  - resourceType: service
    resourceName: db-mock
    port: 5432
    localPort: 5435 # Порт, который вы укажете в pgAdmin (localhost:5435)
  - resourceType: service
    resourceName: db-desc
    port: 5432
    localPort: 5436 # Порт, который вы укажете в pgAdmin (localhost:5436)
  - resourceType: service
    resourceName: db-notification
    port: 5432
    localPort: 5437 # Порт, который вы укажете в pgAdmin (localhost:5437)

deploy:
  kubectl: {}