apiVersion: apps/v1
kind: Deployment
metadata:
  name: desc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desc-service
  template:
    metadata:
      labels:
        app: desc-service
    spec:
      containers:
        - name: desc-service
          image: desc-service
          ports:
            - containerPort: 9902
          env:
            # DB
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-desc:5432/cd_desc
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            # Eureka
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EUREKA_URL
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

            # Auth
            - name: SECURITY_OAUTH2_RESOURCE_USERINFOURI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_URL
---
apiVersion: v1
kind: Service
metadata:
  name: desc-service
spec:
  selector:
    app: desc-service
  ports:
    - port: 9902
      targetPort: 9902