apiVersion: apps/v1
kind: Deployment
metadata:
  name: desc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desc-service
  template:
    metadata:
      labels:
        app: desc-service
    spec:
      containers:
        - name: desc-service
          image: desc-service
          ports:
            - containerPort: 9902
          env:
            # DB
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-desc:5432/cd_desc
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: password

            # Eureka
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka:9009/eureka

            # Auth
            - name: SECURITY_OAUTH2_RESOURCE_USERINFOURI
              value: http://auth-service:9900/user

            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: desc-service
spec:
  selector:
    app: desc-service
  ports:
    - port: 9902
      targetPort: 9902